# Generated by Django 5.0 on 2026-04-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم اليتيم')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('status', models.CharField(default='ينتظر كفالة', max_length=100, verbose_name='الحالة')),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(max_length=100, verbose_name='اسم المتبرع'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='item_type',
            field=models.CharField(max_length=100, verbose_name='نوع التبرع'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(default='قيد التنفيذ', max_length=50, verbose_name='حالة التبرع'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المتطوع'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='points',
            field=models.IntegerField(default=0, verbose_name='النقاط'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='التخصص'),
        ),
    ]
