# Generated by Django 5.0 on 2026-07-04 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_inventoryitem_sponsor_alter_donation_donor_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='orphan',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-points', 'name']},
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='item_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(db_index=True, default='قيد التنفيذ', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='status',
            field=models.CharField(db_index=True, default='ينتظر كفالة', max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='orphan_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='specialty',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'donor_name'], name='donation_status_donor_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_name', 'quantity'], name='inventory_item_quantity_idx'),
        ),
        migrations.AddIndex(
            model_name='orphan',
            index=models.Index(fields=['status', 'age'], name='orphan_status_age_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['name', 'phone'], name='sponsor_name_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['specialty', 'points'], name='volunteer_specialty_points_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='inventory_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orphan',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 0), ('age__lte', 18)), name='orphan_age_between_0_18'),
        ),
        migrations.AddConstraint(
            model_name='volunteer',
            constraint=models.CheckConstraint(check=models.Q(('points__gte', 0)), name='volunteer_points_non_negative'),
        ),
    ]
