# Generated by Codex on 2026-07-24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_volunteerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('need_type', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20)),
                ('required_quantity', models.CharField(blank=True, max_length=100)),
                ('fulfilled_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='open', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_needs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'deadline'], name='need_status_prio_dead_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='need',
            constraint=models.CheckConstraint(check=models.Q(('fulfilled_quantity__gte', 0)), name='need_fulfilled_quantity_non_negative'),
        ),
    ]
