# Generated by Django 5.0 on 2026-08-04 16:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def forwards_status_names(apps, schema_editor):
    Donation = apps.get_model('management', 'Donation')
    VolunteerApplication = apps.get_model('management', 'VolunteerApplication')
    Donation.objects.filter(status='approved').update(status='accepted')
    VolunteerApplication.objects.filter(status='approved').update(status='accepted')


def backwards_status_names(apps, schema_editor):
    Donation = apps.get_model('management', 'Donation')
    VolunteerApplication = apps.get_model('management', 'VolunteerApplication')
    Donation.objects.filter(status='accepted').update(status='approved')
    VolunteerApplication.objects.filter(status='accepted').update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_need'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donation_date', '-id']},
        ),
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='donation',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('financial', 'Financial'), ('in_kind', 'In-kind')], db_index=True, default='in_kind', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='management.need'),
        ),
        migrations.AddField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='item_type',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['user', 'status'], name='donation_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['need', 'status'], name='donation_need_status_idx'),
        ),
        migrations.RunPython(forwards_status_names, backwards_status_names),
    ]
