# Generated by Django 5.2.17 on 2026-08-08 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='need',
            name='care_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='needs', to='management.carehome'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='rating_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='care_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='management.carehome'),
        ),
        migrations.AddConstraint(
            model_name='volunteerapplication',
            constraint=models.CheckConstraint(check=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='volunteer_application_rating_range'),
        ),
        migrations.AddField(
            model_name='visithour',
            name='care_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_hours', to='management.carehome'),
        ),
        migrations.AddIndex(
            model_name='visithour',
            index=models.Index(fields=['care_home', 'weekday'], name='visit_hour_home_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='visithour',
            constraint=models.UniqueConstraint(fields=('care_home', 'weekday', 'start_time'), name='unique_care_home_visit_slot'),
        ),
        migrations.AddConstraint(
            model_name='visithour',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='visit_hour_end_after_start'),
        ),
    ]
