# Generated by Django 5.0 on 2026-08-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_volunteeropportunity_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='need',
            name='required_quantity',
            field=models.CharField(max_length=100),
        ),
    ]
