# Generated by Django 5.0 on 2026-09-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_volunteer_opportunity_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='image',
            field=models.ImageField(blank=True, upload_to='needs/'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='image',
            field=models.ImageField(blank=True, upload_to='volunteer_opportunities/'),
        ),
    ]
