# Generated by Django 5.0 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_uploaded_images_for_needs_and_opportunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
